# This image is published in containers.torproject.org/tpo/applications/tor-browser/base
#
# Whenever there are changes to this file,
# they are autopublished on merge to the tpo/applications/tor-browser repository.
#
# The image is updated roughly once a month when the tor-browser repository is rebased.

FROM containers.torproject.org/tpo/tpa/base-images/python:bookworm

RUN apt-get update && apt-get install -y \
        clang \
        curl \
        git \
        libasound2-dev \
        libdbus-glib-1-dev \
        libgtk-3-dev \
        libpango1.0-dev \
        libpulse-dev \
        libx11-xcb-dev \
        libxcomposite-dev \
        libxcursor-dev \
        libxdamage-dev \
        libxi-dev \
        libxrandr-dev \
        libxtst-dev \
        make \
        m4 \
        mercurial \
        nasm \
        pkgconf \
        unzip \
        x11-utils \
        xvfb \
        xz-utils \
        wget

RUN curl -fsSL https://deb.nodesource.com/setup_lts.x -o nodesource_setup.sh && \
    bash nodesource_setup.sh && \
    apt-get install -y nodejs

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN curl https://sh.rustup.rs -sSf | sh -s -- -y && \
    $HOME/.cargo/bin/cargo install cbindgen
