# This image is published in containers.torproject.org/tpo/applications/tor-browser/{android,desktop}
#
# This image is built and published on CI. The CI job that does this is manual,
# therefore it's up to the developer or reviewer to trigger this CI job when necessary
# e.g. after a RR rebase or big changes to this file.

FROM containers.torproject.org/tpo/tpa/base-images/python:trixie

ARG APPLICATION_CHOICE

RUN apt-get update && apt-get install -y \
        curl \
        git \
        libc6-dev \
        xvfb \
        zlib1g-dev

RUN git clone --single-branch --depth 1 https://gitlab.torproject.org/tpo/applications/tor-browser.git

# Bootstrap will download and install all dependencies required for building / linting / etc.
RUN cd tor-browser && \
    yes | MOZBUILD_STATE_PATH=/var/tmp/mozbuild ./mach bootstrap --application-choice "$APPLICATION_CHOICE" && \
    cd ..

ENV PATH="/var/tmp/mozbuild/clang/bin:/root/.cargo/bin:$PATH"

RUN echo "$APPLICATION_CHOICE" | grep -qi android && \
    rustup target add armv7-linux-androideabi \
        aarch64-linux-android \
        i686-linux-android \
        x86_64-linux-android \
    || true

RUN rm -rf tor-browser && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/tmp/mozbuild/toolchains && \
    rm -rf /var/tmp/mozbuild/indices && \
    rm -rf /var/tmp/mozbuild/android-device
