package org.mozilla.fenix.tor

import androidx.annotation.ColorRes
import androidx.annotation.DrawableRes
import androidx.annotation.StringRes
import org.mozilla.fenix.R

enum class ConnectAssistUiState(
    val progressBarVisible: Boolean,
    @ColorRes val progressBackgroundTintColorResource: Int = R.color.progress_background_tint,
    val backButtonVisible: Boolean,
    val settingsButtonVisible: Boolean,
    val torConnectImageVisible: Boolean,
    @DrawableRes val torConnectImageResource: Int = R.drawable.connect,
    val titleLargeTextViewVisible: Boolean,
    @StringRes val titleLargeTextViewTextStringResource: Int = R.string.connection_assist_tor_connect_title,
    val titleDescriptionVisible: Boolean,
    @StringRes val learnMoreStringResource: Int? = null,
    @StringRes val internetErrorDescription: Int? = null,
    @StringRes val internetErrorDescription1: Int? = null,
    @StringRes val internetErrorDescription2: Int? = null,
    @StringRes val titleDescriptionTextStringResource: Int? = R.string.preferences_tor_network_settings_explanation,
    val quickstartSwitchVisible: Boolean,
    val countryDropDownVisible: Boolean,
    @StringRes val countryDropDownDefaultItem: Int = R.string.connection_assist_automatic_country_detection,
    val torBootstrapButton1Visible: Boolean,
    @StringRes val torBootstrapButton1TextStringResource: Int = R.string.tor_bootstrap_connect,
    val torBootstrapButton1ShouldTryABridge: Boolean = false,
    val torBootstrapButton1ShouldOpenSettings: Boolean = false,
    val torBootstrapButton2Visible: Boolean,
    @StringRes val torBootstrapButton2TextStringResource: Int? = R.string.connection_assist_configure_connection_button,
    val torBootstrapButton2ShouldOpenSettings: Boolean = true,
    val wordmarkLogoVisible: Boolean = false,
    val torBootstrapButton2ShouldRestartApp: Boolean = false,
) {
    Loading(
        progressBarVisible = false,
        backButtonVisible = false,
        settingsButtonVisible = false,
        torConnectImageVisible = false,
        titleLargeTextViewVisible = false,
        titleDescriptionVisible = false,
        quickstartSwitchVisible = false,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = false,
        wordmarkLogoVisible = true,
    ),
    Start(
        progressBarVisible = false,
        backButtonVisible = false,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_tor_connect_title,
        titleDescriptionVisible = true,
        titleDescriptionTextStringResource = R.string.preferences_tor_network_settings_explanation,
        quickstartSwitchVisible = true,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = true,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.connection_assist_configure_connection_button,
        torBootstrapButton2ShouldOpenSettings = true,
    ),
    Bootstrapping(
        progressBarVisible = true,
        backButtonVisible = false,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_connecting_title,
        titleDescriptionVisible = true,
        titleDescriptionTextStringResource = R.string.preferences_tor_network_settings_explanation,
        quickstartSwitchVisible = true,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.btn_cancel,
        torBootstrapButton2ShouldOpenSettings = false,
    ),
    Offline(
        progressBarVisible = true,
        progressBackgroundTintColorResource = R.color.warning_yellow,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.globe_broken,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_internet_error_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_internet_error_learn_more,
        internetErrorDescription = R.string.connection_assist_internet_error_description,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = false,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = true,
        torBootstrapButton1TextStringResource = R.string.connection_assist_internet_error_try_again,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.connection_assist_configure_connection_button,
        torBootstrapButton2ShouldOpenSettings = true,
    ),
    TryingAgain(
        progressBarVisible = true,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_trying_again_waiting_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_internet_error_learn_more,
        internetErrorDescription = R.string.connection_assist_internet_error_description,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = false,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.btn_cancel,
        torBootstrapButton2ShouldOpenSettings = false,
    ),
    ChooseRegion(
        progressBarVisible = true,
        progressBackgroundTintColorResource = R.color.warning_yellow,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect_broken,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_cant_connect_to_tor_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_internet_error_learn_more,
        internetErrorDescription = R.string.connection_assist_try_a_bridge_description,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = false,
        countryDropDownVisible = true,
        torBootstrapButton1Visible = true,
        torBootstrapButton1TextStringResource = R.string.connection_assist_try_a_bridge_button,
        torBootstrapButton1ShouldTryABridge = true,
        torBootstrapButton2Visible = false,
        torBootstrapButton2TextStringResource = null,
        torBootstrapButton2ShouldOpenSettings = true,
    ),
    TryingABridge(
        progressBarVisible = true,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_trying_a_bridge_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_internet_error_learn_more,
        internetErrorDescription = ChooseRegion.internetErrorDescription,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = true,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.btn_cancel,
        torBootstrapButton2ShouldOpenSettings = false,
    ),
    RegionNotFound(
        progressBarVisible = true,
        progressBackgroundTintColorResource = R.color.warning_yellow,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.browser_location,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_location_error_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_location_error_learn_more_link,
        internetErrorDescription = R.string.connection_assist_location_error_description,
        internetErrorDescription1 = R.string.connection_assist_find_bridge_location_description,
        internetErrorDescription2 = R.string.connection_assist_select_country_try_again,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = false,
        countryDropDownVisible = true,
        countryDropDownDefaultItem = R.string.connection_assist_select_country_or_region,
        torBootstrapButton1Visible = true,
        torBootstrapButton1TextStringResource = R.string.connection_assist_try_a_bridge_button,
        torBootstrapButton1ShouldTryABridge = true,
        torBootstrapButton2Visible = false,
        torBootstrapButton2TextStringResource = null,
        torBootstrapButton2ShouldOpenSettings = true,
    ),
    TryingABridgeRegionNotFound(
        progressBarVisible = true,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_trying_a_bridge_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_internet_error_learn_more,
        internetErrorDescription = RegionNotFound.internetErrorDescription,
        internetErrorDescription1 = RegionNotFound.internetErrorDescription1,
        internetErrorDescription2 = RegionNotFound.internetErrorDescription2,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = true,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.btn_cancel,
        torBootstrapButton2ShouldOpenSettings = false,
    ),
    ConfirmRegion(
        progressBarVisible = true,
        progressBackgroundTintColorResource = R.color.warning_yellow,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.browser_location,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_location_check_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_location_error_learn_more_link,
        internetErrorDescription = R.string.connection_assist_location_error_description,
        internetErrorDescription1 = R.string.connection_assist_find_bridge_location_description,
        internetErrorDescription2 = R.string.connection_assist_select_country_try_again,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = false,
        countryDropDownVisible = true,
        countryDropDownDefaultItem = R.string.connection_assist_select_country_or_region,
        torBootstrapButton1Visible = true,
        torBootstrapButton1TextStringResource = R.string.connection_assist_try_a_bridge_button,
        torBootstrapButton1ShouldTryABridge = true,
        torBootstrapButton2Visible = false,
        torBootstrapButton2TextStringResource = null,
        torBootstrapButton2ShouldOpenSettings = true,
    ),
    TryingABridgeConfirmRegion(
        progressBarVisible = true,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_trying_a_bridge_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_internet_error_learn_more,
        internetErrorDescription = ConfirmRegion.internetErrorDescription,
        internetErrorDescription1 = ConfirmRegion.internetErrorDescription1,
        internetErrorDescription2 = ConfirmRegion.internetErrorDescription2,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = true,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.btn_cancel,
        torBootstrapButton2ShouldOpenSettings = false,
    ),
    LastTry(
        progressBarVisible = true,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_last_try_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_location_error_learn_more_link,
        internetErrorDescription = R.string.connection_assist_location_error_description,
        internetErrorDescription1 = R.string.connection_assist_find_bridge_location_description,
        internetErrorDescription2 = R.string.connection_assist_select_country_try_again,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = true,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = false,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.btn_cancel,
        torBootstrapButton2ShouldOpenSettings = false,
    ),
    FinalError(
        progressBarVisible = true,
        progressBackgroundTintColorResource = R.color.warning_yellow,
        backButtonVisible = true,
        settingsButtonVisible = true,
        torConnectImageVisible = true,
        torConnectImageResource = R.drawable.connect_broken,
        titleLargeTextViewVisible = true,
        titleLargeTextViewTextStringResource = R.string.connection_assist_final_error_title,
        titleDescriptionVisible = true,
        learnMoreStringResource = R.string.connection_assist_final_error_learn_more_link,
        internetErrorDescription = R.string.connection_assist_final_error_description1,
        internetErrorDescription1 = R.string.connection_assist_final_error_troubleshoot_connection_link,
        titleDescriptionTextStringResource = null,
        quickstartSwitchVisible = false,
        countryDropDownVisible = false,
        torBootstrapButton1Visible = true,
        torBootstrapButton1TextStringResource = R.string.connection_assist_configure_connection_button,
        torBootstrapButton1ShouldOpenSettings = true,
        torBootstrapButton2Visible = true,
        torBootstrapButton2TextStringResource = R.string.mozac_lib_crash_dialog_button_restart,
        torBootstrapButton2ShouldOpenSettings = false,
        torBootstrapButton2ShouldRestartApp = true,
    )
}
