# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        'cid': '{2537313c-e120-408c-a2f6-86e6e1bdf899}',
        'contract_ids': ['@torproject.org/tor-service;1'],
        'interfaces': ['ITorService'],
        'constructor': 'torproject::NewTorService',
        'headers': ['torproject/TorService.h'],
        'js_name': 'tor',
    },
]
