# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

Classes = [
    {
        "cid": "{b4a1073c-9e3c-4ce7-b13b-c100f5c64ccb}",
        "contract_ids": [
            "@torproject.org/selective-saving-mode;1",
        ],
        "esModule": "moz-src:///toolkit/components/selectivesavingmode/SelectiveSavingMode.sys.mjs",
        "constructor": "SelectiveSavingPrefController",
    }
]
