#!/usr/bin/env python3
# PYTHON_ARGCOMPLETE_OK
"""
Useful tools for working on tor-browser repository.
"""

import argparse
import atexit
import functools
import json
import os
import re
import subprocess
import sys
import tempfile
import termios
import urllib.request
from collections.abc import Callable, Iterable, Iterator
from types import ModuleType
from typing import Any, NotRequired, TypedDict, TypeVar

argcomplete: None | ModuleType = None
try:
    import argcomplete
except ImportError:
    pass

GIT_PATH = "/usr/bin/git"
UPSTREAM_URLS = {
    "tor-browser": [
        "https://gitlab.torproject.org/tpo/applications/tor-browser.git",
        "git@gitlab.torproject.org:tpo/applications/tor-browser.git",
    ],
    "mullvad-browser": [
        "https://gitlab.torproject.org/tpo/applications/mullvad-browser.git",
        "git@gitlab.torproject.org:tpo/applications/mullvad-browser.git",
    ],
}
FIXUP_PREPROCESSOR_EDITOR = "git-rebase-fixup-preprocessor"
USER_EDITOR_ENV_NAME = "GIT_REBASE_FIXUP_PREPROCESSOR_USER_EDITOR"


class TbDevException(Exception):
    pass


def git_run(
    args: list[str], check: bool = True, env: None | dict[str, str] = None
) -> None:
    """
    Run a git command with output sent to stdout.
    :param args: The arguments to pass to git.
    :param check: Whether to check for success.
    :param env: Optional environment to set.
    """
    if env is not None:
        tmp_env = dict(os.environ)
        for key, value in env.items():
            tmp_env[key] = value
        env = tmp_env
    try:
        subprocess.run([GIT_PATH, *args], check=check, env=env)
    except subprocess.CalledProcessError as err:
        raise TbDevException(str(err)) from err


def git_get(args: list[str], strip: bool = True, check: bool = True) -> str:
    """
    Return the output from a git command.
    :param args: The arguments to send to git.
    :param strip: Whether to strip the whitespace from the output.
    :param check: Whether to check for success.
    :returns: The stdout.
    """
    try:
        git_process = subprocess.run(
            [GIT_PATH, *args], text=True, stdout=subprocess.PIPE, check=check
        )
    except subprocess.CalledProcessError as err:
        raise TbDevException(str(err)) from err
    ret = git_process.stdout
    if strip:
        ret = ret.strip()
    return ret


def git_lines(args: list[str]) -> Iterator[str]:
    """
    Yields the non-empty lines returned by the git command.
    :param args: The arguments to send to git.
    :yield: The lines.
    """
    for line in git_get(args, strip=False).split("\n"):
        if not line:
            continue
        yield line


@functools.cache
def get_local_root() -> str:
    """
    Get the path for the tor-browser root directory.
    :returns: The local root.
    """
    try:
        # Make sure we have a matching remote in this git repository.
        if get_upstream_details()["is-browser-repo"] == "True":
            return git_get(["rev-parse", "--show-toplevel"])
        else:
            return ""
    except TbDevException:
        return ""


@functools.cache
def get_upstream_details() -> dict[str, str]:
    """
    Get details about the upstream repository.
    :returns: The details.
    """
    remote_urls = {
        remote: git_get(["remote", "get-url", remote])
        for remote in git_lines(["remote"])
    }

    matches = {
        remote: repo
        for repo, url_list in UPSTREAM_URLS.items()
        for url in url_list
        for remote, fetch_url in remote_urls.items()
        if fetch_url == url
    }

    is_browser_repo = len(matches) > 0
    details = {"is-browser-repo": str(is_browser_repo)}

    origin_remote_repo = matches.get("origin", None)
    upstream_remote_repo = matches.get("upstream", None)

    if origin_remote_repo is not None:
        if upstream_remote_repo is None:
            details["remote"] = "origin"
            details["repo-name"] = origin_remote_repo
        # Else, both "upstream" and "origin" point to a remote repo. Not clear
        # which should be used.
    elif upstream_remote_repo is not None:
        details["remote"] = "upstream"
        details["repo-name"] = upstream_remote_repo
    elif len(matches) == 1:
        remote = next(iter(matches.keys()))
        details["remote"] = remote
        details["repo-name"] = matches[remote]
    # Else, the upstream is ambiguous.

    return details


class Reference:
    """Represents a git reference to a commit."""

    _REFS_REGEX = re.compile(r"refs/[a-z]+/")

    def __init__(self, full_name: str, commit: str) -> None:
        """
        :param full_name: The full reference name. E.g. "refs/tags/MyTag".
        :param commit: The commit hash for the commit this reference points to.
        """
        match = self.__class__._REFS_REGEX.match(full_name)
        if not match:
            raise ValueError(f"Invalid reference name {full_name}")
        self.full_name = full_name
        self.name = full_name[match.end() :]
        self.commit = commit


def get_refs(ref_type: str, name_start: str) -> Iterator[Reference]:
    """
    Get a list of references that match the given conditions.
    :param ref_type: The ref type to search for ("tag" or "remote" or "head").
    :param name_start: The ref name start to match against.
    :yield: The matching references.
    """
    if ref_type == "tag":
        ref_start = "refs/tags/"
    elif ref_type == "remote":
        ref_start = "refs/remotes/"
    elif ref_type == "head":
        ref_start = "refs/heads/"
    else:
        raise TypeError(f"Unknown type {ref_type}")

    fstring = "%(*objectname),%(objectname),%(refname)"
    pattern = f"{ref_start}{name_start}**"

    def line_to_ref(line: str) -> Reference:
        [objectname_reference, objectname, ref_name] = line.split(",", 2)
        # For annotated tags, the objectname_reference is non-empty and points
        # to an actual commit.
        # For remotes, heads and lightweight tags, the objectname_reference will
        # be empty and objectname will point directly to the commit.
        return Reference(ref_name, objectname_reference or objectname)

    return (
        line_to_ref(line)
        for line in git_lines(["for-each-ref", f"--format={fstring}", pattern])
    )


def get_firefox_ref(search_from: str) -> Reference:
    """
    Search for the commit that comes from firefox.
    :param search_from: The commit to search backwards from.
    :returns: The firefox reference.
    """
    # Only search a limited history that should include the FIREFOX_ tag.
    search_commits = [c for c in git_lines(["rev-list", "-1000", search_from])]

    firefox_tag_prefix = "FIREFOX_"

    existing_tags = list(get_refs("tag", firefox_tag_prefix))
    for commit in search_commits:
        for ref in existing_tags:
            if commit == ref.commit:
                return ref

    # Might just need to fetch tags from the remote.
    upstream = get_upstream_details().get("remote", None)
    if upstream:
        remote_ref: None | Reference = None
        search_index = len(search_commits)
        # Search the remote for a tag that is in our history.
        # We want to avoid triggering a long fetch, so we just want to grab the
        # tag that already points to a commit in our history.
        for line in git_lines(
            ["ls-remote", upstream, f"refs/tags/{firefox_tag_prefix}*"]
        ):
            objectname, name = line.split("\t", 1)
            for index in range(search_index):
                if search_commits[index] == objectname:
                    # Remove trailing "^{}" for commits pointed to by
                    # annotated tags.
                    remote_ref = Reference(re.sub(r"\^\{\}$", "", name), objectname)
                    # Only continue to search for references that are even
                    # closer to `search_from`.
                    search_index = index
                    break
        if remote_ref is not None:
            # Get a local copy of just this tag.
            git_run(["fetch", "--no-tags", upstream, "tag", remote_ref.name])
            return ref

    raise TbDevException("Unable to find FIREFOX_ tag")


def get_upstream_tracking_branch(search_from: str) -> str:
    """
    :param search_from: The commit reference.
    :returns: The upstream branch reference name.
    """
    return git_get(["rev-parse", "--abbrev-ref", f"{search_from}@{{upstream}}"])


def get_upstream_basis_commit(search_from: str) -> str:
    """
    Get the first common ancestor of search_from that is also in its upstream
    branch.
    :param search_from: The commit reference.
    :returns: The upstream commit hash.
    """
    upstream_branch = get_upstream_tracking_branch(search_from)
    commit = git_get(["merge-base", search_from, upstream_branch])
    # Verify that the upstream commit shares the same firefox basis. Otherwise,
    # this would indicate that the upstream is on an early or later FIREFOX
    # base.
    upstream_firefox = get_firefox_ref(upstream_branch).commit
    search_firefox = get_firefox_ref(search_from).commit
    if upstream_firefox != search_firefox:
        raise TbDevException(
            f"Upstream of {search_from} has a different FIREFOX base. "
            "You might want to set the upstream tracking branch to a new value."
        )
    return commit


class FileChange:
    """Represents a git change to a commit."""

    def __init__(self, status: str, path: str, new_path: str) -> None:
        """
        :param status: The file change status used within git diff. E.g. "M" for
          modified, or "D" for deleted.
        :param path: The source file path.
        :param new_path: The file path after the change.
        """
        self.status = status
        self.path = path
        self.new_path = new_path


RAW_DIFF_PATH_PATTERN = r"(?P<path>[^\0]*)\0"
RAW_DIFF_LINE_REGEX = re.compile(
    r":[0-7]+ [0-7]+ [0-9a-f]+ [0-9a-f]+ (?P<status>[ADMTUXRC])[0-9]*\0"
    + RAW_DIFF_PATH_PATTERN
)
RAW_DIFF_PATH_REGEX = re.compile(RAW_DIFF_PATH_PATTERN)


def parse_raw_diff_line(raw_output: str) -> tuple[FileChange, int]:
    """
    Parse the --raw diff output from git.
    :param raw_output: The raw output.
    :returns: The change for this line, and the offset for the end of the raw
      diff line.
    """
    match = RAW_DIFF_LINE_REGEX.match(raw_output)
    if not match:
        raise ValueError(f"Invalid raw output: {raw_output[:50]}...")
    path = os.path.relpath(os.path.join(get_local_root(), match.group("path")))
    status = match.group("status")
    if status in ("R", "C"):
        match = RAW_DIFF_PATH_REGEX.match(raw_output, pos=match.end())
        if not match:
            raise ValueError(f"Invalid raw output for rename: {raw_output[:50]}...")
        new_path = os.path.relpath(os.path.join(get_local_root(), match.group("path")))
    else:
        new_path = path

    return FileChange(status, path, new_path), match.end()


def get_changed_files(
    from_commit: None | str = None, staged: bool = False
) -> Iterator[FileChange]:
    """
    Get a list of file changes relative to the current working directory that have
    been changed since 'from_commit' (non-inclusive).
    :param from_commit: The commit to compare against, otherwise use the git
      diff default.
    :param staged: Whether to limit the diff to staged changes.
    :yield: The file changes.
    """
    args = ["diff", "-z", "--raw"]
    if staged:
        args.append("--staged")
    if from_commit:
        args.append(from_commit)
    raw_output = git_get(args, strip=False)
    while raw_output:
        file_change, end = parse_raw_diff_line(raw_output)
        yield file_change
        raw_output = raw_output[end:]


def file_contains(filename: str, regex: re.Pattern[str]) -> bool:
    """
    Return whether the file is a utf-8 text file containing the regular
    expression given by 'regex'.
    :param filename: The file path.
    :param regex: The pattern to search for.
    :returns: Whether the pattern was matched.
    """
    with open(filename, encoding="utf-8") as file:
        try:
            for line in file:
                if regex.search(line):
                    return True
        except UnicodeDecodeError:
            # Not a text file
            pass
    return False


def get_gitlab_default() -> str:
    """
    Get the name of the default branch on gitlab.
    :returns: The branch name.
    """
    repo_name = get_upstream_details().get("repo-name", None)
    if repo_name is None:
        raise TbDevException("Cannot determine the repository name")
    query = f"""
      query {{
        project(fullPath: "tpo/applications/{repo_name}") {{
          repository {{ rootRef }}
        }}
      }}
    """
    request_data = {"query": re.sub(r"\s+", "", query)}
    gitlab_request = urllib.request.Request(
        "https://gitlab.torproject.org/api/graphql",
        headers={
            "Content-Type": "application/json",
            "User-Agent": "",
        },
        data=json.dumps(request_data).encode("ascii"),
    )

    with urllib.request.urlopen(gitlab_request, timeout=20) as response:
        default = json.load(response)["data"]["project"]["repository"]["rootRef"]
        assert isinstance(default, str)
        return default


def within_browser_root() -> bool:
    """
    :returns: Whether we are with the tor browser root.
    """
    root = get_local_root()
    if not root:
        return False
    return os.path.commonpath([os.getcwd(), root]) == root


# * -------------------- *
# | Methods for commands |
# * -------------------- *


def show_firefox_commit(_args: argparse.Namespace) -> None:
    """
    Print the tag name and commit for the last firefox commit below the current
    HEAD.
    """
    ref = get_firefox_ref("HEAD")
    print(ref.full_name)
    print(ref.commit)


def show_upstream_basis_commit(_args: argparse.Namespace) -> None:
    """
    Print the last upstream commit for the current HEAD.
    """
    print(get_upstream_basis_commit("HEAD"))


def show_log(args: argparse.Namespace) -> None:
    """
    Show the git log between the current HEAD and the last firefox commit.
    """
    commit = get_firefox_ref("HEAD").commit
    git_run(["log", f"{commit}..HEAD", *args.gitargs], check=False)


def show_files_containing(args: argparse.Namespace) -> None:
    """
    List all the files that that have been modified for tor browser, that also
    contain a regular expression.
    """
    try:
        regex = re.compile(args.regex)
    except re.error as err:
        raise TbDevException(f"{args.regex} is not a valid python regex") from err

    for file_change in get_changed_files(get_firefox_ref("HEAD").commit):
        path = file_change.new_path
        if not os.path.isfile(path):
            # deleted ofile
            continue
        if file_contains(path, regex):
            print(path)


def show_changed_files(_args: argparse.Namespace) -> None:
    """
    List all the files that have been modified relative to upstream.
    """
    for file_change in get_changed_files(get_upstream_basis_commit("HEAD")):
        print(file_change.new_path)


def lint_changed_files(args: argparse.Namespace) -> None:
    """
    Lint all the files that have been modified relative to upstream.
    """
    os.chdir(get_local_root())
    file_list = [
        f.new_path
        for f in get_changed_files(get_upstream_basis_commit("HEAD"))
        if os.path.isfile(f.new_path)  # Not deleted
    ]
    # We add --warnings since clang only reports whitespace issues as warnings.
    subprocess.run(
        ["./mach", "lint", "--warnings", "soft", *args.lintargs, *file_list],
        check=False,
    )


# TODO: replace with "prompt_user[T](..., T]) -> T" after python 3.12 is the
# minimum mach version.
T = TypeVar("T")


def prompt_user(prompt: str, convert: Callable[[str], T]) -> T:
    """
    Ask the user for some input.
    :param prompt: The prompt to show the user.
    :param convert: A method to convert the response into a type. Should
      throw `ValueError` if the user should be re-prompted for a valid input.
    :returns: The first valid user response.
    """
    while True:
        # Flush out stdin.
        termios.tcflush(sys.stdin, termios.TCIFLUSH)
        print(prompt, end="")
        sys.stdout.flush()
        try:
            return convert(sys.stdin.readline().strip())
        except ValueError:
            # Continue to prompt.
            pass


def binary_reply_default_no(value: str) -> bool:
    """
    Process a 'y' or 'n' reply, defaulting to 'n' if empty.
    :param value: The user input.
    :returns: Whether the answer is yes.
    """
    if value == "":
        return False
    if value.lower() == "y":
        return True
    if value.lower() == "n":
        return False
    raise ValueError()


def get_fixup_for_file(filename: str, firefox_commit: str) -> str | None:
    """
    Find the commit the given file should fix up.
    :param filename: The file path.
    :param firefox_commit: The commit hash for the firefox commit.
    :returns: The chosen commit to fixup, or `None` if it should be skipped.
    """

    def parse_log_line(line: str) -> dict[str, str]:
        [commit, short_ref, title] = line.split(",", 2)
        return {"commit": commit, "short-ref": short_ref, "title": title}

    options = [
        parse_log_line(line)
        for line in git_lines(
            [
                "log",
                "--pretty=format:%H,%h,%s",
                f"{firefox_commit}..HEAD",
                "--",
                filename,
            ]
        )
    ]
    if not options:
        print(f"No commit found for {filename}")
        return None

    def valid_index(val: str) -> None | str | tuple[bool, str]:
        if val == "d":
            return val

        is_patch = val.startswith("p")
        if is_patch:
            val = val[1:]

        # May raise a ValueError.
        as_index = int(val)
        if as_index < 0 or as_index > len(options):
            raise ValueError()

        if as_index == 0:
            if is_patch:
                raise ValueError()
            return None

        return (is_patch, options[as_index - 1]["commit"])

    while True:
        print(f"For {filename}:\n")
        print("  \x1b[1m0\x1b[0m: None")
        for index, opt in enumerate(options):
            print(
                f"  \x1b[1m{index + 1}\x1b[0m: "
                + f"\x1b[1;38;5;212m{opt['short-ref']}\x1b[0m "
                + opt["title"]
            )
        print("")
        response = prompt_user(
            "Choose an <index> to fixup, or '0' to skip this file, "
            "or 'd' to view the pending diff, "
            "or 'p<index>' to view the patch for the index: ",
            valid_index,
        )
        if response is None:
            # Skip this file.
            return None

        if response == "d":
            git_run(["diff", "--", filename])
            continue

        assert isinstance(response, tuple)
        view_patch, commit = response
        if view_patch:
            git_run(["log", "-p", "-1", commit, "--", filename])
            continue

        return commit


def auto_fixup(_args: argparse.Namespace) -> None:
    """
    Automatically find and fix up commits using the current unstaged changes.
    """
    # Only want to search as far back as the firefox commit.
    firefox_commit = get_firefox_ref("HEAD").commit

    staged_files = [c.new_path for c in get_changed_files("HEAD", staged=True)]
    if staged_files:
        raise TbDevException(f"Have already staged files: {staged_files}")

    fixups: dict[str, list[str]] = {}
    for filename in (c.new_path for c in get_changed_files("HEAD")):
        commit = get_fixup_for_file(filename, firefox_commit)
        if commit is None:
            continue
        if commit not in fixups:
            fixups[commit] = [filename]
        else:
            fixups[commit].append(filename)
        print("")

    for commit, files in fixups.items():
        print("")
        git_run(["add", *files])
        git_run(["commit", f"--fixup={commit}"])
        print("")

        if prompt_user(
            "Edit fixup commit message? (y/\x1b[4mn\x1b[0m)", binary_reply_default_no
        ):
            git_run(["commit", "--amend"])


def clean_fixups(_args: argparse.Namespace) -> None:
    """
    Perform an interactive rebase that automatically applies fixups, similar to
    --autosquash but also works on fixups of fixups.
    """
    user_editor = git_get(["var", "GIT_SEQUENCE_EDITOR"])
    sub_editor = os.path.join(
        os.path.dirname(os.path.realpath(__file__)), FIXUP_PREPROCESSOR_EDITOR
    )

    git_run(
        ["rebase", "--interactive"],
        check=False,
        env={"GIT_SEQUENCE_EDITOR": sub_editor, USER_EDITOR_ENV_NAME: user_editor},
    )


def show_default(_args: argparse.Namespace) -> None:
    """
    Print the default branch name from gitlab.
    """
    default_branch = get_gitlab_default()
    upstream = get_upstream_details().get("remote", None)
    if upstream is None:
        raise TbDevException("Cannot determine the upstream remote")
    print(f"{upstream}/{default_branch}")


def branch_from_default(args: argparse.Namespace) -> None:
    """
    Fetch the default gitlab branch from upstream and create a new local branch.
    """
    default_branch = get_gitlab_default()
    upstream = get_upstream_details().get("remote", None)
    if upstream is None:
        raise TbDevException("Cannot determine the upstream remote")

    git_run(["fetch", upstream, default_branch])
    git_run(
        [
            "switch",
            "--create",
            args.branchname,
            "--track",
            f"{upstream}/{default_branch}",
        ]
    )


def move_to_default(args: argparse.Namespace) -> None:
    """
    Fetch the default gitlab branch from upstream and move the specified
    branch's commits on top. A new branch will be created tracking the default
    branch, and the old branch will be renamed with a suffix for the old
    tracking branch. This method will switch to the new branch, but will avoid
    switching to the old branch to prevent triggering a CLOBBER build.
    """
    branch_name = args.branch
    if branch_name is None:
        # Use current branch as default.
        try:
            branch_name = git_get(["branch", "--show-current"])
        except IndexError:
            raise TbDevException("No current branch")

    current_upstream_branch = get_upstream_tracking_branch(branch_name)
    default_branch = get_gitlab_default()
    upstream = get_upstream_details().get("remote", None)
    if upstream is None:
        raise TbDevException("Cannot determine the upstream remote")

    git_run(["fetch", upstream, default_branch])

    new_upstream_branch = f"{upstream}/{default_branch}"
    if current_upstream_branch == new_upstream_branch:
        print(
            f"{branch_name} is already set to track the default branch {new_upstream_branch}."
        )
        return

    # We want to avoid checking out the old branch because this can cause
    # mozilla ./mach to do a CLOBBER build.
    # Instead we create a new branch with the same name and cherry pick.
    current_basis = get_upstream_basis_commit(branch_name)
    old_branch_name = branch_name + "-" + get_firefox_ref(branch_name).name

    print(f"Moving old branch {branch_name} to {old_branch_name}")
    git_run(["branch", "-m", branch_name, old_branch_name])

    try:
        git_run(["switch", "--create", branch_name, "--track", new_upstream_branch])
    except subprocess.CalledProcessError as err:
        print(f"Moving {old_branch_name} back to {branch_name}")
        git_run(["branch", "-m", old_branch_name, branch_name])
        raise err

    # Set check to False since cherry-pick might fail due to a merge conflict.
    git_run(["cherry-pick", f"{current_basis}..{old_branch_name}"], check=False)


def show_range_diff(args: argparse.Namespace) -> None:
    """
    Show the range diff between two branches, from their firefox bases.
    """
    firefox_commit_1 = get_firefox_ref(args.branch1).commit
    firefox_commit_2 = get_firefox_ref(args.branch2).commit
    git_run(
        [
            "range-diff",
            f"{firefox_commit_1}..{args.branch1}",
            f"{firefox_commit_2}..{args.branch2}",
        ],
        check=False,
    )


def show_diff_diff(args: argparse.Namespace) -> None:
    """
    Show the diff between the diffs of two branches, relative to their firefox
    bases.
    """
    try:
        diff_tool = next(git_lines(["config", "--get", "diff.tool"]))
    except StopIteration:
        raise TbDevException("No diff.tool configured for git")

    # Filter out parts of the diff we expect to be different.
    index_regex = re.compile(r"index [0-9a-f]{12}\.\.[0-9a-f]{12}")
    lines_regex = re.compile(r"@@ -[0-9]+,[0-9]+ \+[0-9]+,[0-9]+ @@(?P<rest>.*)")

    def save_diff(branch: str) -> str:
        firefox_commit = get_firefox_ref(branch).commit
        file_desc, file_name = tempfile.mkstemp(
            text=True, prefix=f'{branch.split("/")[-1]}-'
        )
        # Register deleting the file at exit.
        atexit.register(os.remove, file_name)

        diff_process = subprocess.Popen(
            [GIT_PATH, "diff", f"{firefox_commit}..{branch}"],
            stdout=subprocess.PIPE,
            text=True,
        )

        with os.fdopen(file_desc, "w") as file:
            assert diff_process.stdout is not None
            for line in diff_process.stdout:
                if index_regex.match(line):
                    # Fake data that will match.
                    file.write("index ????????????..????????????\n")
                    continue
                lines_match = lines_regex.match(line)
                if lines_match:
                    # Fake data that will match.
                    file.write("@@ ?,? ?,? @@" + lines_match.group("rest"))
                    continue
                file.write(line)

        status = diff_process.poll()
        if status != 0:
            raise TbDevException(f"git diff exited with status {status}")

        return file_name

    file_1 = save_diff(args.branch1)
    file_2 = save_diff(args.branch2)
    subprocess.run([diff_tool, file_1, file_2], check=False)


# * -------------------- *
# | Command line parsing |
# * -------------------- *


def branch_complete(prefix: str, **_kwargs: Any) -> list[str]:
    """
    Complete the argument with a branch name.
    """
    if not within_browser_root():
        return []
    try:
        branches = [ref.name for ref in get_refs("head", "")]
        branches.extend(ref.name for ref in get_refs("remote", ""))
        branches.append("HEAD")
    except Exception:
        return []
    return [br for br in branches if br.startswith(prefix)]


parser = argparse.ArgumentParser()
subparsers = parser.add_subparsers(required=True)


class ArgConfig(TypedDict):
    help: str
    metavar: NotRequired[str]
    nargs: NotRequired[str]
    completer: NotRequired[Callable[[str], list[str]]]


class CommandConfig(TypedDict):
    func: Callable[[argparse.Namespace], None]
    args: NotRequired[dict[str, ArgConfig]]


all_commands: dict[str, CommandConfig] = {
    "show-upstream-basis-commit": {
        "func": show_upstream_basis_commit,
    },
    "changed-files": {
        "func": show_changed_files,
    },
    "lint-changed-files": {
        "func": lint_changed_files,
        "args": {
            "lintargs": {
                "help": "argument to pass to ./mach lint",
                "metavar": "-- lint-arg",
                "nargs": "*",
            },
        },
    },
    "auto-fixup": {
        "func": auto_fixup,
    },
    "clean-fixups": {
        "func": clean_fixups,
    },
    "show-default": {
        "func": show_default,
    },
    "branch-from-default": {
        "func": branch_from_default,
        "args": {
            "branchname": {
                "help": "the name for the new local branch",
                "metavar": "<branch-name>",
            },
        },
    },
    "move-to-default": {
        "func": move_to_default,
        "args": {
            "branch": {
                "help": "the branch to move, else uses the current branch",
                "metavar": "<branch>",
                "nargs": "?",
                "completer": branch_complete,
            },
        },
    },
    "show-firefox-commit": {
        "func": show_firefox_commit,
    },
    "log": {
        "func": show_log,
        "args": {
            "gitargs": {
                "help": "argument to pass to git log",
                "metavar": "-- git-log-arg",
                "nargs": "*",
            },
        },
    },
    "branch-range-diff": {
        "func": show_range_diff,
        "args": {
            "branch1": {
                "help": "the first branch to compare",
                "metavar": "<branch-1>",
                "completer": branch_complete,
            },
            "branch2": {
                "help": "the second branch to compare",
                "metavar": "<branch-2>",
                "completer": branch_complete,
            },
        },
    },
    "branch-diff-diff": {
        "func": show_diff_diff,
        "args": {
            "branch1": {
                "help": "the first branch to compare",
                "metavar": "<branch-1>",
                "completer": branch_complete,
            },
            "branch2": {
                "help": "the second branch to compare",
                "metavar": "<branch-2>",
                "completer": branch_complete,
            },
        },
    },
    "files-containing": {
        "func": show_files_containing,
        "args": {
            "regex": {"help": "the regex that the files must contain"},
        },
    },
}

for name, command_config in all_commands.items():
    help_message = command_config["func"].__doc__
    assert isinstance(help_message, str)
    help_message = re.sub(r"\s+", " ", help_message).strip()
    sub = subparsers.add_parser(name, help=help_message)
    sub.set_defaults(func=command_config["func"])
    for arg, keywords in command_config.get("args", {}).items():
        completer = None
        if "completer" in keywords:
            completer = keywords["completer"]
            del keywords["completer"]
        sub_arg = sub.add_argument(arg, **keywords)
        if completer is not None and argcomplete is not None:
            sub_arg.completer = completer  # type: ignore

if argcomplete is not None:
    argcomplete.autocomplete(parser)

try:
    if not within_browser_root():
        raise TbDevException("Must be within a browser directory")
    parsed_args = parser.parse_args()

    parsed_args.func(parsed_args)
except TbDevException as err:
    print(f"\x1b[1m{err}\x1b[0m", file=sys.stderr)
